### ISSUE TITLE
AttributeError: 'PoseHigherResolutionNet' object has no attribute 'module'

### ISSUE THREAD

**Issue by Janisco-cv** [HRNet/HigherHRNet-Human-Pose-Estimation#60]
when I run the "dist_train.py", I got a error:
Traceback (most recent call last):
  File "tools/dist_train.py", line 322, in <module>
    main()
  File "tools/dist_train.py", line 123, in main
    tb_log_dir
  File "tools/dist_train.py", line 306, in main_worker
    'best_state_dict': model.module.state_dict(),
  File "/root/miniconda3/envs/hh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'PoseHigherResolutionNet' object has no attribute 'module'
My configuration environment is CUDA9.0+pytorch1.0.1+tensorboardX1.6, I guess this problem may have something to do with the pytorch version. I haven't solved this problem yet. Has anyone solved this problem?

**Comment by Janisco-cv** [comment]
I have successfully solved the proble.

**Comment by hdasd** [comment]
Hello, I have the same problem. How did you solve this problem (Python 1.2.0, torch vision 0.2.1, cuda10.0)?
