### ISSUE TITLE
When I  'python tools/dist_train.py     --cfg experiments/coco/higher_hrnet/w32_512_adam_lr1e-3.yaml '，I have a problem

### ISSUE THREAD

**Issue by happydog555** [HRNet/HigherHRNet-Human-Pose-Estimation#76]
Traceback (most recent call last):
  File "tools/dist_train.py", line 319, in <module>
    main()
  File "tools/dist_train.py", line 114, in main
    args=(ngpus_per_node, args, final_output_dir, tb_log_dir)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/lm/POSE_ROOT/tools/dist_train.py", line 196, in main_worker
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/home/lm/anaconda3/lib/python3.7/site-packages/tensorboardX/writer.py", line 794, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 285, in graph
    trace = torch.jit.trace(model, args)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 955, in trace
    check_tolerance, strict, _force_outplace, _module_class)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1103, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 787, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 2234, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 787, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 2234, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 787, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 2234, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 787, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 2234, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 787, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 2234, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 787, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/lm/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 2195, in __init__
    assert(isinstance(orig, torch.nn.Module))
AssertionError

**Comment by lxyism** [comment]
hello, i meet the same question, do you fix it?

**Comment by happydog555** [comment]
I modified tensorboardX version 2.1 to 0.8 as below.
pip install tensorboardX==0.8




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lxyism"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 下午3:22
收件人: "HRNet/HigherHRNet-Human-Pose-Estimation"<HigherHRNet-Human-Pose-Estimation@noreply.github.com&gt;; 
抄送: "15045559"<15045559@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HRNet/HigherHRNet-Human-Pose-Estimation] When I  &#39;python tools/dist_train.py     --cfg experiments/coco/higher_hrnet/w32_512_adam_lr1e-3.yaml &#39;，I have a problem (#76)





 
hello, i meet the same question, do you fix it?

**Comment by lxyism** [comment]
ok, thx
